apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: unit-test-go
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.37.0"
    tekton.dev/categories: "Automation"
    tekton.dev/displayName: "Test unit test golang"
spec:
  description: |-
    Unit test golang
  resources:
    inputs:
      - name: git
        type: git
        targetPath: go/src/github.com/kyma-project/test-infra
  steps:
    - image: "eu.gcr.io/kyma-project/test-infra/buildpack-golang:v20221028-60f0f5a2"
      name: "unit-test-go"
      timeout: 15m
      workingDir: "$(resources.inputs.git.path)"
      env:
        - name: GOPATH
          value: "/workspace/go"
      command:
        - "go"
      args:
        - "test"
        - "-cover"
        - "./..."
      resources:
        requests:
          memory: 400Mi
          cpu: 1
