apiVersion: "tekton.dev/v1alpha1"
kind: "Task"
metadata:
  name: "good-bye"
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.37.0"
    tekton.dev/categories: "Automation"
    tekton.dev/displayName: "Say good bye"
spec:
  description: |-
    Say good bye.
  steps:
    - image: "alpine"
      name: "listing"
      script: |
        #!/bin/sh
        
        echo "Good bye"
