apiVersion: "tekton.dev/v1alpha1"
kind: "Task"
metadata:
  name: "hello"
  labels:
    app.kubernetes.io/version: "0.1"
    annotations:
      tekton.dev/pipelines.minVersion: "0.37.0"
      tekton.dev/categories: Automation
      tekton.dev/tags: "ansible, cli"
      tekton.dev/displayName: "Test Task Hello World"
spec:
  description: |-
    test task hello world
  steps:
    - image: "alpine"
      name: "echo"
      resources: {}
      script: "#!/bin/sh\necho \"Hello World\"\n"
